version: '3'

services:

  client:
    restart: always
    container_name: CCG_Client
    build: ./mongodb
    links:
      - server
    depends_on:
      - server
    volumes:
      - ./client:/app/client
      - /app/client/node_modules

  mongo:
    image: mongo
    container_name: mongo
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Singapore
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db

  server:
    restart: always
    container_name: servers
    build:
      context: ./server
      dockerfile: Dockerfile.Production
    environment:
      - TZ=Asia/Singapore
    ports:
      - '5000:5000'
    links:
      - mongo
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
    expose:
      - "5000"

  nginx:
    restart: always
    build: ./nginx
    container_name: nginxs
    environment:
      - TZ=Asia/Singapore
    links:
      - server
    depends_on:
      - server
      - client
    volumes:
      - ./client/dist/:/usr/share/nginx/html
    ports:
      - "80:80"
