#!/bin/bash

if [ $1 = 'docker-publish' ]
then cmd="docker build -t server -f ./Dockerfile.Production . && docker run -d --name server -p 5000:5000 -t server"

elif [ $1 = 'docker-stop' ]
then cmd="docker stop server && docker rm server"

elif [ $1 = 'docker-bash' ]
then cmd="docker exec -it server bash"

elif [ $1 = 'help' ]
then
  echo Commands:
  echo docker-publish: run production server in docker
  echo docker-stop: stop docker production server
  echo docker-bash: go in docker server bash command
  exit

else
  echo Command \"$1\" not found.
  exit
fi

echo Running command \"$1\".
echo "$" $cmd
eval $cmd
